spring.application.name=RitaMPC

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

home.assistant.websocket.url=ws://100.67.102.49:8123/api/websocket
home.assistant.websocket.access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiMjEzZTFiZDc0M2M0ZTg0OTUwNGUyYTg0YmZjYzVlOCIsImlhdCI6MTc2OTcwMTg1MSwiZXhwIjoyMDg1MDYxODUxfQ.k_GDc8tn2GGdQzmibEKfQ2qmYeYCcsBEiiO0xDOlClY

booster.model.location=C:/Users/WelJo/PycharmProjects/RitaML/models

# https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints.exposing
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always